export const TYPES = {
    IN_PROGRESS: "IN_PROGRESS",
    LOADING: "LOADING",
    EVENTS_LOADED: "EVENTS_LOADED",
    EVENT_LOADED: "EVENT_LOADED",
    FEED_LOADED: "FEED_LOADED",
    CONVERSATIONS_LOADED: "CONVERSATIONS_LOADED",
    FILTERS_APPLIED: "FILTERS_APPLIED"
};