export const TYPES = {
    LOADING: "LOADING",
    EVENTS_LOADED: "EVENTS_LOADED",
    EVENT_LOADED: "EVENT_LOADED",
    FEED_LOADED: "FEED_LOADED",
    CONVERSATIONS_LOADED: "CONVERSATIONS_LOADED",
    FILTERS_APPLIED: "FILTERS_APPLIED",
    LOCALE_APPLIED: "LOCALE_APPLIED",
    ME_LOADED: "ME_LOADED",
    LOGIN_ERRORS: "LOGIN_ERRORS",
    LOGIN_RESETED: "LOGIN_RESETED"
};